### ISSUE TITLE
The end of the demo test/demo does not show the ending cutscene

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#237] opened 2016-05-13 18:43 UTC
When you go to complete the demo test and/or the demo, the demoend.roq does not play at the end of the single player. In the real Q3A demotest/demo, this cutscene does play at the end.

**Comment by ensiform** [comment] 2016-05-14 14:00
Presumably the issue is because it's set to play a different name in q3/mint-arena for the full version.  You'd have to find the code that calls the video cinematic at the end and tell it which should be played.

**Comment by zturtleman** [comment] 2016-05-14 15:39
Fixed in https://github.com/zturtleman/mint-arena/commit/d2aded53f911c3d8827caa68c7ab7cf303dd6ebc.

**Closed by zturtleman** 2016-05-14 15:39 UTC

**Comment by zturtleman** [comment] 2016-05-14 15:50
Ugh, never mind let's use a cvar instead. `set ui_demoq3 1`. https://github.com/zturtleman/mint-arena/commit/b4fd6bc971583329026bf0e4aa24f22f60b75b89

**Comment by coltongit** [comment] 2016-05-14 16:37
Might wanna set that cvar as default for both the demo and the demotest
@zturtleman.

**Comment by coltongit** [comment] 2016-05-14 16:38
And make sure that's in both the demoq3/demoq3test mint-game.settings
please.

**Comment by zturtleman** [comment] 2016-05-14 17:08
https://github.com/zturtleman/spearmint-patch-data/commit/0bf146516b58685e0f7c2b498663518b5a3ed988

**Comment by coltongit** [comment] 2016-05-14 17:09
Thanks.
