### ISSUE TITLE
Small bug with ordering teammates to kill enemies in Spearmint/ioq3/classic Q3

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#272] opened 2016-07-08 21:49 UTC
As said on forum.clover.moe:
The bug is as follows:
1. Start a TDM on any map (I used q3dm7)
2. Have at least one person on both teams (I tested with at least 4 bots on Blue & 1 on Red)
3. Have everyone on your team kill the only bot on Red (might also happen with just one teammate, untested however)
4. If you didn't give these teammates a new order, after a while, "ERROR: PlayerName: player name out of range" or similar will occur. Bug happens on Q3 1.32c & possibly even the original source code has this bug. Unknown if the bug happens on earlier versions of Q3.

**Comment by KuehnhammerTobias** [comment] 2016-07-09 22:22
Hmm, currently I'm not able to reproduce the bug. What do you mean by person? Must it be a human or is a bot also meant as person here? Do you mean client in general?
I tested as you said, with persons (humans) and with bots. Regardless what I do, the message doesn't appear.
Are all of your teammates told (give order) to kill the bot on the opposite team? You said you have to give the teammates order to avoid this bug, any specific TDM order?
Sorry for my questions, I'm interested in this bug, but can't reproduce it atm!.

**Comment by zturtleman** [comment] 2016-07-10 07:37
Start game client and run:

g_gametype 3; teampref blue; devmap q3dm7;

After map loads run:

addbot Major 4 blue; addbot Doom 4 blue; addbot Sarge 4 red; say_team everyone kill Sarge; timescale 10;

Wait until message is printed.

Fixed in https://github.com/zturtleman/mint-arena/commit/9418069927bdac6d43794963793a5cd40b243b7f

**Closed by zturtleman** 2016-07-10 07:37 UTC
Labels: bug

**Comment by coltongit** [comment] 2016-07-10 19:32
I also forgot to mention that this bug also exists in ioq3, @zturtleman. Mind fixing it there too, if possible?
